baseURL = "https://vijayanant.com/"
title = "Vijay Anant"
languageCode = "en-us"
[params]
description = "Engineering Leader & Product Builder"
author = "Vijay Anantharamaiah"
portrait = "images/contact-image.png"
googleAnalytics = "G-XNSPFRLLVH"
image = "images/contact-image.png"
contactEmail = "hello@vijayanant.com"
enableCodeCopyButton = true
enableRelatedPosts = true
enableNewsletter = true
enableSearch = true
enableThemeToggle = true

[params.newsletter]
title = "The Anant Loop"
description = "Articles on crafting quality software and building high-performing teams that last."
author = "Vijay Anant"
[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/vijayanant/"
[[params.social]]
name = "GitHub"
url = "https://github.com/vijayanant"
[[params.social]]
name = "Twitter"
url = "https://twitter.com/vijayanant"

[related]
threshold = 80
includeNewer = true
toLower = true

[[related.indices]]
name = "categories"
weight = 180

[[related.indices]]
name = "tags"
weight = 120

[[related.indices]]
name = "title"
weight = 15

[[related.indices]]
name = "date"
weight = 10

[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
groupXML = false
keepCSSPseudoClasses = false
keepComments = false
keepCSSVariables = false
keepQuotes = false
newLine = false

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "RSS"]
section = ["HTML", "RSS"]

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[markup]
[markup.highlight]
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[security]
[security.funcs]
getenv = ["HUGO_"]
